name: Deploy Debian
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: ros2_mediapipe

      - name: Build Debian package
        uses: ichiro-its/ros2-build-debian-action@main
        with:
          unique-version: true

      - name: Deploy Debian package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "package/*.deb"
          target: "~/temp/threeal/ros2_mediapipe/"
          rm: true

      - name: Prepare Debian package in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ~/repository/debian
            reprepro includedeb threeal ~/temp/threeal/ros2_mediapipe/package/*.deb
            rm -rf ~/temp/threeal/ros2_mediapipe/
